### ISSUE TITLE
java.net.SocketTimeoutException: Read timed out

### ISSUE THREAD

**Issue by andrei1010gaming** [GeyserMC/GeyserWiki#145]
idk what happened but heres the full error:
java.net.SocketTimeoutException: Read timed out
        at sun.nio.ch.NioSocketImpl.timedRead(NioSocketImpl.java:283) ~[?:?]
        at sun.nio.ch.NioSocketImpl.implRead(NioSocketImpl.java:309) ~[?:?]
        at sun.nio.ch.NioSocketImpl.read(NioSocketImpl.java:350) ~[?:?]
        at sun.nio.ch.NioSocketImpl$1.read(NioSocketImpl.java:803) ~[?:?]
        at java.net.Socket$SocketInputStream.read(Socket.java:966) ~[?:?]
        at sun.security.ssl.SSLSocketInputRecord.read(SSLSocketInputRecord.java:484) ~[?:?]
        at sun.security.ssl.SSLSocketInputRecord.readHeader(SSLSocketInputRecord.java:478) ~[?:?]
        at sun.security.ssl.SSLSocketInputRecord.bytesInCompletePacket(SSLSocketInputRecord.java:70) ~[?:?]
        at sun.security.ssl.SSLSocketImpl.readApplicationRecord(SSLSocketImpl.java:1465) ~[?:?]
        at sun.security.ssl.SSLSocketImpl$AppInputStream.read(SSLSocketImpl.java:1069) ~[?:?]
        at java.io.BufferedInputStream.fill(BufferedInputStream.java:244) ~[?:?]
        at java.io.BufferedInputStream.read1(BufferedInputStream.java:284) ~[?:?]
        at java.io.BufferedInputStream.read(BufferedInputStream.java:343) ~[?:?]
        at sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:824) ~[?:?]
        at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:759) ~[?:?]
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1688) ~[?:?]
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1589) ~[?:?]
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:224) ~[?:?]
        at org.geysermc.geyser.util.WebUtils.getJson(WebUtils.java:78) ~[Geyser-Spigot.jar:?]
        at org.geysermc.geyser.util.VersionCheckUtils.lambda$checkForGeyserUpdate$0(VersionCheckUtils.java:63) ~[Geyser-Spigot.jar:?]
        at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?]
        at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?]
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?]
        at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?]
        at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?]
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?]
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?]

**Comment by Camotoy** [comment]
This is safe to ignore - it just means that your server is having a tough time reaching our update server. But in the future, please use the main Geyser repository to report issues. Thanks!

**Comment by andrei1010gaming** [comment]
> This is safe to ignore - it just means that your server is having a tough time reaching our update server. But in the future, please use the main Geyser repository to report issues. Thanks!

No problem!
P.S: i just clicked a link from the official GeyserMC page
