### ISSUE TITLE
Question:Velocity issue

### ISSUE THREAD

**Issue by Djdiwxn** [GeyserMC/GeyserWiki#170]
[18:27:09 ERROR]: java.nio.channels.ClosedChannelException
[18:27:09 ERROR]:       at io.netty.channel.local.LocalChannel.doWrite(LocalChannel.java:368)
[18:27:09 ERROR]:       at io.netty.channel.AbstractChannel$AbstractUnsafe.flush0(AbstractChannel.java:931)
[18:27:09 ERROR]:       at io.netty.channel.AbstractChannel$AbstractUnsafe.flush(AbstractChannel.java:895)
[18:27:09 ERROR]:       at io.netty.channel.DefaultChannelPipeline$HeadContext.flush(DefaultChannelPipeline.java:1372)
[18:27:09 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:921)
[18:27:09 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:907)
[18:27:09 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:893)
[18:27:09 ERROR]:       at io.netty.channel.ChannelDuplexHandler.flush(ChannelDuplexHandler.java:127)
[18:27:09 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:923)
[18:27:09 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:941)
[18:27:09 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:966)
[18:27:09 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:934)
[18:27:09 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:984)
[18:27:09 ERROR]:       at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1025)
[18:27:09 ERROR]:       at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:306)
[18:27:09 ERROR]:       at com.github.steveice10.packetlib.tcp.TcpSession.send(TcpSession.java:250)
[18:27:09 ERROR]:       at com.github.steveice10.mc.protocol.ClientListener.connected(ClientListener.java:140)
[18:27:09 ERROR]:       at com.github.steveice10.packetlib.event.session.ConnectedEvent.call(ConnectedEvent.java:31)
[18:27:09 ERROR]:       at com.github.steveice10.packetlib.tcp.TcpSession.callEvent(TcpSession.java:146)
[18:27:09 ERROR]:       at com.github.steveice10.packetlib.tcp.TcpSession.channelActive(TcpSession.java:357)
[18:27:09 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:262)
[18:27:09 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:238)
[18:27:09 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.fireChannelActive(AbstractChannelHandlerContext.java:231)
[18:27:09 ERROR]:       at io.netty.channel.ChannelInboundHandlerAdapter.channelActive(ChannelInboundHandlerAdapter.java:69)
[18:27:09 ERROR]:       at io.netty.handler.timeout.IdleStateHandler.channelActive(IdleStateHandler.java:271)
[18:27:09 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:260)
[18:27:09 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:238)
[18:27:09 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.fireChannelActive(AbstractChannelHandlerContext.java:231)
[18:27:09 ERROR]:       at io.netty.channel.ChannelInboundHandlerAdapter.channelActive(ChannelInboundHandlerAdapter.java:69)
[18:27:09 ERROR]:       at org.geysermc.geyser.network.netty.LocalSession$2.channelActive(LocalSession.java:137)
[18:27:09 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:262)
[18:27:09 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:238)
[18:27:09 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.fireChannelActive(AbstractChannelHandlerContext.java:231)
[18:27:09 ERROR]:       at io.netty.channel.DefaultChannelPipeline$HeadContext.channelActive(DefaultChannelPipeline.java:1398)
[18:27:09 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:258)
[18:27:09 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:238)
[18:27:09 ERROR]:       at io.netty.channel.DefaultChannelPipeline.fireChannelActive(DefaultChannelPipeline.java:895)
[18:27:09 ERROR]:       at io.netty.channel.local.LocalChannel$3.run(LocalChannel.java:185)
[18:27:09 ERROR]:       at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
[18:27:09 ERROR]:       at io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54)
[18:27:09 ERROR]:       at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
[18:27:09 ERROR]:       at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[18:27:09 ERROR]:       at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
[18:27:09 ERROR]:       at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by onebeastchris** [comment]
This is the GitHub page for the Geyser wiki; not the Geyser project. Additionally, you've been asked to provide logs in the discord support channel - please do so.
