### ISSUE TITLE
Question:Error

### ISSUE THREAD

**Issue by jeosalih** [GeyserMC/GeyserWiki#255]
Hi, 
Raspberry pi 5, raspberryos 64bit, orecle java 21, paper 1.20.4, geyzer build 463

[12:41:51 INFO]: ******************************************
[12:41:51 INFO]: 
[12:41:51 INFO]: Geyser sürüm 2.2.2-SNAPSHOT (git-master-c91ee53) yükleniyor
[12:41:51 INFO]: 
[12:41:51 INFO]: ******************************************
[12:42:04 ERROR]: Could not pass event ServerLoadEvent to Geyser-Spigot v2.2.2-SNAPSHOT
java.lang.ExceptionInInitializerError: null
	at org.geysermc.geyser.network.netty.GeyserServer.<init>(GeyserServer.java:115) ~[?:?]
	at org.geysermc.geyser.GeyserImpl.startInstance(GeyserImpl.java:405) ~[?:?]
	at org.geysermc.geyser.GeyserImpl.initialize(GeyserImpl.java:237) ~[?:?]
	at org.geysermc.geyser.GeyserImpl.start(GeyserImpl.java:789) ~[?:?]
	at org.geysermc.geyser.platform.spigot.GeyserSpigotPlugin.onGeyserEnable(GeyserSpigotPlugin.java:214) ~[?:?]
	at org.geysermc.geyser.platform.spigot.GeyserSpigotPlugin$1.onServerLoaded(GeyserSpigotPlugin.java:198) ~[?:?]
	at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:40) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:git-Paper-450]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.20.4.jar:git-Paper-450]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.20.4.jar:git-Paper-450]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:672) ~[paper-1.20.4.jar:git-Paper-450]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:431) ~[paper-1.20.4.jar:git-Paper-450]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:309) ~[paper-1.20.4.jar:git-Paper-450]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1131) ~[paper-1.20.4.jar:git-Paper-450]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[paper-1.20.4.jar:git-Paper-450]
	at java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.NumberFormatException: For input string: "20+rpt"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:67) ~[?:?]
	at java.lang.Integer.parseInt(Integer.java:662) ~[?:?]
	at java.lang.Integer.parseInt(Integer.java:778) ~[?:?]
	at org.geysermc.geyser.network.netty.Bootstraps.fromString(Bootstraps.java:93) ~[?:?]
	at org.geysermc.geyser.network.netty.Bootstraps.<clinit>(Bootstraps.java:60) ~[?:?]
	... 18 more

**Comment by onebeastchris** [comment]
Known issue at the moment, see https://github.com/GeyserMC/Geyser/issues/4492 and the pull request linked there
