### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by OSzwed** [GeyserMC/GeyserWiki#275]
[20:00:24] [Server thread/INFO]: [Geyser-Spigot] Enabling Geyser-Spigot v2.3.1-SNAPSHOT                                 
[20:00:25] [Server thread/ERROR]: Error occurred while enabling Geyser-Spigot v2.3.1-SNAPSHOT (Is it up to date?)       java.lang.NullPointerException: Cannot invoke "org.geysermc.geyser.GeyserImpl.getLogger()" because "this.geyser" is null                                                                                                                                
at org.geysermc.geyser.command.GeyserCommandManager.register(GeyserCommandManager.java:127) ~[?:?]                      
at org.geysermc.geyser.command.GeyserCommandManager.registerBuiltInCommand(GeyserCommandManager.java:118) ~[?:?]                                                                                                                                
at org.geysermc.geyser.command.GeyserCommandManager.init(GeyserCommandManager.java:74) ~[?:?]                           
at org.geysermc.geyser.platform.spigot.GeyserSpigotPlugin.onEnable(GeyserSpigotPlugin.java:169) ~[?:?]                  
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[spigot-api-1.20.6-R0.1-SNAPSHOT.jar:?]           
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342) ~[spigot-api-1.20.6-R0.1-SNAPSHOT.jar:?]                                                                                                                     
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:491) ~[spigot-api-1.20.6-R0.1-SNAPSHOT.jar:?]                                                                                                                    
at org.bukkit.craftbukkit.v1_20_R4.CraftServer.enablePlugin(CraftServer.java:541) ~[spigot-1.20.6-R0.1-SNAPSHOT.jar:4149-Spigot-e2c1eee-4e7d749]                                                                                                
at org.bukkit.craftbukkit.v1_20_R4.CraftServer.enablePlugins(CraftServer.java:455) ~[spigot-1.20.6-R0.1-SNAPSHOT.jar:4149-Spigot-e2c1eee-4e7d749]                                                                                               
at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:634) ~[spigot-1.20.6-R0.1-SNAPSHOT.jar:4149-Spigot-e2c1eee-4e7d749]                                                                                                     
at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:419) ~[spigot-1.20.6-R0.1-SNAPSHOT.jar:4149-Spigot-e2c1eee-4e7d749]                                                                                                      
at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:265) ~[spigot-1.20.6-R0.1-SNAPSHOT.jar:4149-Spigot-e2c1eee-4e7d749]                                                                                                    
at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:1010) ~[spigot-1.20.6-R0.1-SNAPSHOT.jar:4149-Spigot-e2c1eee-4e7d749]                                                                                                             
at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:311) ~[spigot-1.20.6-R0.1-SNAPSHOT.jar:4149-Spigot-e2c1eee-4e7d749]                                                                                                  
at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]

**Comment by onebeastchris** [comment]
We provide support for Geyser related issues on our discord server - please join it and ask in the support channel there.
